# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('anio', models.IntegerField()),
                ('sexo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('seccion', models.CharField(max_length=60)),
                ('aula', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Pensun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('materias', models.ManyToManyField(through='pensun.Asignacion', to='pensun.Materia')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('especialiadad', models.CharField(max_length=60)),
                ('sexo', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='asignacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pensun.Materia'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='pensun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pensun.Pensun'),
        ),
    ]
